import { createFileRoute } from "@tanstack/react-router";
import { ServiceLanding } from "@/components/ServiceLanding";
import image from "@/assets/service-cad.jpg";

const url = "https://www.sintesi3d.it/progettazione-cad";
const description = "Progettazione CAD 3D, modellazione parametrica, disegni tecnici e Design for Additive Manufacturing per componenti meccanici e prodotti industriali.";
export const Route = createFileRoute("/progettazione-cad")({ head: () => ({ meta: [{title:"Progettazione CAD 3D e modellazione meccanica | Sintesi 3D"},{name:"description",content:description},{property:"og:title",content:"Progettazione CAD 3D | Sintesi 3D"},{property:"og:description",content:description},{property:"og:url",content:url},{property:"og:image",content:image}], links:[{rel:"canonical",href:url}] }), component: Page });

function Page(){return <ServiceLanding eyebrow="Progettazione CAD 3D" title="Progettiamo componenti" accent="pronti per essere prodotti." intro="Dal concept al modello parametrico e al disegno esecutivo. Sviluppiamo componenti meccanici, attrezzature e prodotti ottimizzati per lavorazioni tradizionali o additive manufacturing." image={image} imageAlt="Progettazione CAD 3D di un componente meccanico" benefits={["Modellazione parametrica e superfici complesse", "Disegni tecnici quotati e tavole esecutive", "Design for Additive Manufacturing e ottimizzazione topologica", "Esperienza applicativa in aerospace, motorsport e ferroviario"]} applications={[{title:"Sviluppo prodotto",description:"Trasformiamo requisiti, schizzi e idee in modelli CAD verificabili e producibili."},{title:"Ottimizzazione",description:"Riduciamo massa, parti e vincoli produttivi mantenendo funzione, rigidezza e assemblabilità."},{title:"Industrializzazione",description:"Prepariamo tavole, tolleranze, accoppiamenti e dati necessari per produzione e controllo."}]} process={[{title:"Requisiti",description:"Definiamo funzione, interfacce, carichi, materiali, processo produttivo e criteri di accettazione."},{title:"Progettazione",description:"Sviluppiamo il modello parametrico con revisioni intermedie e verifiche di producibilità."},{title:"Consegna",description:"Forniamo modelli e tavole nei formati concordati, con supporto alla prototipazione e produzione."}]} faq={[{question:"Quali formati CAD consegnate?",answer:"In base al progetto possiamo consegnare STEP, IGES, STL, Parasolid e formati nativi concordati, oltre a tavole PDF e DWG/DXF."},{question:"Potete partire da uno schizzo o da un’idea?",answer:"Sì. Raccogliamo requisiti e vincoli e trasformiamo il concept in un modello 3D, passando attraverso revisioni condivise prima della consegna finale."},{question:"Progettate anche per la stampa 3D?",answer:"Sì. Applichiamo criteri DfAM per sfruttare l’additive manufacturing, limitare supporti e deformazioni e ottenere un componente funzionale e producibile."},{question:"Realizzate anche il prototipo?",answer:"Sì. Progettazione CAD e stampa 3D possono essere gestite dallo stesso team, riducendo passaggi e tempi tra modifica del modello e verifica fisica."}]} schema={{"@context":"https://schema.org","@type":"Service",name:"Servizio di progettazione CAD 3D",serviceType:"Progettazione CAD e modellazione meccanica",provider:{"@type":"LocalBusiness",name:"Sintesi 3D",url:"https://www.sintesi3d.it"},areaServed:{"@type":"Country",name:"Italia"},url,description}}/>}
