import { createFileRoute } from "@tanstack/react-router";
import { ServiceLanding } from "@/components/ServiceLanding";
import image from "@/assets/service-scan.jpg";

const url = "https://www.sintesi3d.it/scansione-3d";
const description = "Servizio di scansione 3D professionale fino a 0,02 mm per componenti, ricambi, controllo dimensionale e reverse engineering, anche presso il cliente.";

export const Route = createFileRoute("/scansione-3d")({
  head: () => ({ meta: [{ title: "Scansione 3D professionale e rilievo 3D | Sintesi 3D" }, { name: "description", content: description }, { property: "og:title", content: "Scansione 3D professionale | Sintesi 3D" }, { property: "og:description", content: description }, { property: "og:url", content: url }, { property: "og:image", content: image }], links: [{ rel: "canonical", href: url }] }),
  component: Page,
});

function Page() { return <ServiceLanding eyebrow="Scansione 3D" title="Digitalizziamo il reale con" accent="precisione misurabile." intro="Acquisiamo geometrie complesse con scanner 3D a luce strutturata e laser. Consegniamo mesh, nuvole di punti, report dimensionali o modelli pronti per il successivo reverse engineering." image={image} imageAlt="Scansione 3D professionale di un componente meccanico" benefits={["Precisione dichiarata fino a 0,02 mm", "Scansione presso il nostro studio o in sede cliente", "Output STL, OBJ, PLY e modelli CAD STEP", "Color map e confronto scansione-CAD"]} applications={[{title:"Reverse engineering",description:"Digitalizzazione di ricambi, componenti obsoleti e geometrie prive di disegno tecnico."},{title:"Controllo dimensionale",description:"Confronto tra parte prodotta e modello nominale con visualizzazione delle deviazioni."},{title:"Archivi e repliche",description:"Acquisizione di oggetti, stampi, modelli e superfici per documentazione o riproduzione."}]} process={[{title:"Preparazione",description:"Valutiamo dimensioni, materiale, finitura superficiale, accessibilità e precisione richiesta."},{title:"Acquisizione",description:"Eseguiamo le scansioni necessarie, allineiamo i dati e verifichiamo la copertura geometrica."},{title:"Elaborazione",description:"Puliamo la mesh e consegniamo il formato richiesto o proseguiamo con il modello CAD."}]} faq={[{question:"Quanto è precisa una scansione 3D?",answer:"La precisione dipende da strumento, volume, superficie e condizioni di acquisizione. Per i componenti compatibili possiamo raggiungere una precisione fino a 0,02 mm."},{question:"Potete scansionare il pezzo presso la nostra azienda?",answer:"Sì. Quando il componente non può essere trasportato o il lavoro lo richiede, valutiamo interventi di scansione direttamente presso il cliente."},{question:"Una scansione produce automaticamente un file STEP?",answer:"No. Lo scanner produce una mesh o una nuvola di punti. Per ottenere un modello STEP parametrico e modificabile è necessario un processo di reverse engineering CAD."},{question:"Scansionate superfici nere o riflettenti?",answer:"Sì, adottando preparazione e tecniche di acquisizione adeguate. La fattibilità viene valutata prima del lavoro in base al materiale e alla finitura."}]} schema={{"@context":"https://schema.org","@type":"Service",name:"Servizio di scansione 3D professionale",serviceType:"Scansione e rilievo 3D",provider:{"@type":"LocalBusiness",name:"Sintesi 3D",url:"https://www.sintesi3d.it"},areaServed:{"@type":"Country",name:"Italia"},url,description}} />; }
