import { createFileRoute, Link } from "@tanstack/react-router";

import { Layout } from "@/components/Layout";

export const Route = createFileRoute("/en/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Notice — Sintesi 3D" },
      {
        name: "description",
        content:
          "English privacy notice for Sintesi 3D contact form, file uploads and website services.",
      },
    ],
  }),

  component: PrivacyNoticeEn,
});

function PrivacyNoticeEn() {
  return (
    <Layout>
      <section className="border-b border-border/60 py-24 md:py-32">
        <div className="mx-auto max-w-4xl px-6 lg:px-10">
          <span className="tech-label">// English notice</span>

          <h1 className="mt-6 font-display text-5xl font-semibold leading-[1] md:text-7xl">
            Privacy Notice
          </h1>

          <p className="mt-8 text-lg leading-relaxed text-muted-foreground">
            This English privacy notice explains how Sintesi 3D processes personal
            data submitted through the website, especially through the contact form
            and file upload feature.
          </p>

          <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
            The official iubenda-generated Privacy Policy is available in Italian.
            This English version is provided for transparency and convenience.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-4xl px-6 py-20 lg:px-10">
        <div className="space-y-12 text-muted-foreground">
          <Block title="1. Data controller">
            <p>
              The data controller is{" "}
              <strong className="text-foreground">Sintesi 3D di Michela Rozza</strong>,
              sole proprietorship, represented by the owner{" "}
              <strong className="text-foreground">Rozza Michela</strong>, operating
              through the website and the trade name{" "}
              <strong className="text-foreground">Sintesi 3D</strong>.
            </p>

            <p className="mt-3">VAT number: 03247910643</p>
            <p className="mt-3">Owner tax code: RZZMHL86H63I073S</p>
            <p className="mt-3">
              Registered office / tax domicile: Via S. Croce 48, 83020 Sperone
              (AV), Italy.
            </p>

            <p className="mt-3">
              Privacy contact email:{" "}
              <a
                href="mailto:info@sintesi3d.it"
                className="text-primary underline underline-offset-4"
              >
                info@sintesi3d.it
              </a>
            </p>
          </Block>

          <Block title="2. Personal data collected">
            <p>
              Through the contact form, the website may collect the following data:
              name, email address, phone number, company name, selected service,
              message content and any technical files uploaded by the user.
            </p>

            <p className="mt-3">
              Uploaded files may include images, PDFs, STL, STEP, STP, OBJ, ZIP,
              RAR or other project-related technical files voluntarily submitted by
              the user.
            </p>

            <p className="mt-3">
              Users are invited not to submit special categories of personal data,
              unnecessary third-party data or information that is not required to
              evaluate the request.
            </p>
          </Block>

          <Block title="3. Purpose of processing">
            <p>
              The data is processed exclusively to reply to contact requests,
              evaluate technical or commercial enquiries, prepare quotations and
              manage pre-contractual communication with the user.
            </p>
          </Block>

          <Block title="4. Legal basis">
            <p>
              The processing is based on the user&apos;s request to be contacted and
              on the need to take steps prior to entering into a possible contract.
              Where applicable, processing may also be based on the legitimate
              interest of Sintesi 3D in managing business communications, technical
              enquiries, security, diagnostics and abuse prevention.
            </p>
          </Block>

          <Block title="5. File uploads and temporary storage">
            <p>
              Files uploaded through the contact form are stored temporarily in a
              private Cloudflare R2 storage bucket. The bucket is not public and the
              files are not freely accessible from the Internet.
            </p>

            <p className="mt-3">
              Uploaded files are accessible to Sintesi 3D through temporary signed
              links generated by the website backend. These links are used only to
              manage the request submitted by the user.
            </p>

            <p className="mt-3">
              Uploaded files are kept for a maximum of 30 days and then deleted,
              unless strictly necessary technical, legal, defensive or contractual
              reasons related to the user&apos;s request require otherwise.
            </p>
          </Block>

          <Block title="6. Email delivery">
            <p>
              The website uses Resend to send contact form submissions to{" "}
              <a
                href="mailto:info@sintesi3d.it"
                className="text-primary underline underline-offset-4"
              >
                info@sintesi3d.it
              </a>
              . The email may contain the form data, technical metadata and
              temporary links to uploaded files.
            </p>
          </Block>

          <Block title="7. Website infrastructure and technical logs">
            <p>
              The website is hosted and delivered through Cloudflare services,
              including Cloudflare Workers and Cloudflare R2. These services help
              deliver the website, process the contact request and temporarily store
              uploaded files.
            </p>

            <p className="mt-3">
              Cloudflare Workers Observability/Logs may be used for technical
              security, diagnostics, monitoring, error detection and abuse
              prevention. Technical logs may include IP address, timestamp, requested
              URL, request metadata and application errors. These logs are not used
              for profiling or marketing.
            </p>
          </Block>

          <Block title="8. International data transfers">
            <p>
              Cloudflare and Resend may process data outside the European Economic
              Area, including in the United States. Where required, such transfers
              are based on the providers&apos; Data Processing Agreements, Standard
              Contractual Clauses and other safeguards provided by applicable data
              protection law.
            </p>
          </Block>

          <Block title="9. Retention period">
            <p>
              Contact requests are kept for the time necessary to respond to the
              enquiry and manage any related commercial, technical, administrative,
              legal or tax follow-up.
            </p>

            <p className="mt-3">
              Uploaded files sent through the contact form are kept for a maximum of
              30 days.
            </p>
          </Block>

          <Block title="10. Data subject rights">
            <p>
              Users may request access, rectification, deletion, restriction of
              processing, objection to processing or portability of their personal
              data, where applicable under data protection law.
            </p>

            <p className="mt-3">
              Requests can be sent to{" "}
              <a
                href="mailto:info@sintesi3d.it"
                className="text-primary underline underline-offset-4"
              >
                info@sintesi3d.it
              </a>
              .
            </p>
          </Block>

          <Block title="11. Official Italian policy">
            <p>
              The official Privacy Policy generated through iubenda is available
              here:
            </p>

            <p className="mt-3">
              <a
                href="https://www.iubenda.com/privacy-policy/82947247"
                className="iubenda-white iubenda-noiframe iubenda-embed text-primary underline underline-offset-4"
                title="Privacy Policy"
              >
                Italian Privacy Policy
              </a>
            </p>
          </Block>

          <div className="border-t border-border/60 pt-10">
            <Link
              to="/en"
              className="font-mono text-xs uppercase tracking-[0.25em] text-primary transition-smooth hover:text-foreground"
            >
              ← Back to English website
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-2xl font-semibold text-foreground">{title}</h2>

      <div className="mt-4 text-base leading-relaxed">{children}</div>
    </section>
  );
}
