/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as ReverseEngineeringRouteImport } from './routes/reverse-engineering'
import { Route as ProgettiRouteImport } from './routes/progetti'
import { Route as PrivacyContattiRouteImport } from './routes/privacy-contatti'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as ProgettiReverseEngineeringStaffaAutomotiveRouteImport } from './routes/progetti/reverse-engineering-staffa-automotive'
import { Route as EnServicesRouteImport } from './routes/en/services'
import { Route as EnProjectsRouteImport } from './routes/en/projects'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as EnCookiePolicyRouteImport } from './routes/en/cookie-policy'
import { Route as EnContactPrivacyRouteImport } from './routes/en/contact-privacy'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as ApiDownloadRouteImport } from './routes/api/download'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseEngineeringRoute = ReverseEngineeringRouteImport.update({
  id: '/reverse-engineering',
  path: '/reverse-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiRoute = ProgettiRouteImport.update({
  id: '/progetti',
  path: '/progetti',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyContattiRoute = PrivacyContattiRouteImport.update({
  id: '/privacy-contatti',
  path: '/privacy-contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiReverseEngineeringStaffaAutomotiveRoute =
  ProgettiReverseEngineeringStaffaAutomotiveRouteImport.update({
    id: '/reverse-engineering-staffa-automotive',
    path: '/reverse-engineering-staffa-automotive',
    getParentRoute: () => ProgettiRoute,
  } as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/en/services',
  path: '/en/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsRoute = EnProjectsRouteImport.update({
  id: '/en/projects',
  path: '/en/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCookiePolicyRoute = EnCookiePolicyRouteImport.update({
  id: '/en/cookie-policy',
  path: '/en/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactPrivacyRoute = EnContactPrivacyRouteImport.update({
  id: '/en/contact-privacy',
  path: '/en/contact-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/privacy-contatti': typeof PrivacyContattiRoute
  '/progetti': typeof ProgettiRouteWithChildren
  '/reverse-engineering': typeof ReverseEngineeringRoute
  '/servizi': typeof ServiziRoute
  '/api/contact': typeof ApiContactRoute
  '/api/download': typeof ApiDownloadRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/contact-privacy': typeof EnContactPrivacyRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/services': typeof EnServicesRoute
  '/progetti/reverse-engineering-staffa-automotive': typeof ProgettiReverseEngineeringStaffaAutomotiveRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/privacy-contatti': typeof PrivacyContattiRoute
  '/progetti': typeof ProgettiRouteWithChildren
  '/reverse-engineering': typeof ReverseEngineeringRoute
  '/servizi': typeof ServiziRoute
  '/api/contact': typeof ApiContactRoute
  '/api/download': typeof ApiDownloadRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/contact-privacy': typeof EnContactPrivacyRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/services': typeof EnServicesRoute
  '/progetti/reverse-engineering-staffa-automotive': typeof ProgettiReverseEngineeringStaffaAutomotiveRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/privacy-contatti': typeof PrivacyContattiRoute
  '/progetti': typeof ProgettiRouteWithChildren
  '/reverse-engineering': typeof ReverseEngineeringRoute
  '/servizi': typeof ServiziRoute
  '/api/contact': typeof ApiContactRoute
  '/api/download': typeof ApiDownloadRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/contact-privacy': typeof EnContactPrivacyRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/services': typeof EnServicesRoute
  '/progetti/reverse-engineering-staffa-automotive': typeof ProgettiReverseEngineeringStaffaAutomotiveRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/privacy-contatti'
    | '/progetti'
    | '/reverse-engineering'
    | '/servizi'
    | '/api/contact'
    | '/api/download'
    | '/en/about'
    | '/en/contact'
    | '/en/contact-privacy'
    | '/en/cookie-policy'
    | '/en/privacy'
    | '/en/projects'
    | '/en/services'
    | '/progetti/reverse-engineering-staffa-automotive'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/privacy-contatti'
    | '/progetti'
    | '/reverse-engineering'
    | '/servizi'
    | '/api/contact'
    | '/api/download'
    | '/en/about'
    | '/en/contact'
    | '/en/contact-privacy'
    | '/en/cookie-policy'
    | '/en/privacy'
    | '/en/projects'
    | '/en/services'
    | '/progetti/reverse-engineering-staffa-automotive'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/privacy-contatti'
    | '/progetti'
    | '/reverse-engineering'
    | '/servizi'
    | '/api/contact'
    | '/api/download'
    | '/en/about'
    | '/en/contact'
    | '/en/contact-privacy'
    | '/en/cookie-policy'
    | '/en/privacy'
    | '/en/projects'
    | '/en/services'
    | '/progetti/reverse-engineering-staffa-automotive'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  PrivacyContattiRoute: typeof PrivacyContattiRoute
  ProgettiRoute: typeof ProgettiRouteWithChildren
  ReverseEngineeringRoute: typeof ReverseEngineeringRoute
  ServiziRoute: typeof ServiziRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnContactPrivacyRoute: typeof EnContactPrivacyRoute
  EnCookiePolicyRoute: typeof EnCookiePolicyRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnProjectsRoute: typeof EnProjectsRoute
  EnServicesRoute: typeof EnServicesRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-engineering': {
      id: '/reverse-engineering'
      path: '/reverse-engineering'
      fullPath: '/reverse-engineering'
      preLoaderRoute: typeof ReverseEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti': {
      id: '/progetti'
      path: '/progetti'
      fullPath: '/progetti'
      preLoaderRoute: typeof ProgettiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-contatti': {
      id: '/privacy-contatti'
      path: '/privacy-contatti'
      fullPath: '/privacy-contatti'
      preLoaderRoute: typeof PrivacyContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti/reverse-engineering-staffa-automotive': {
      id: '/progetti/reverse-engineering-staffa-automotive'
      path: '/reverse-engineering-staffa-automotive'
      fullPath: '/progetti/reverse-engineering-staffa-automotive'
      preLoaderRoute: typeof ProgettiReverseEngineeringStaffaAutomotiveRouteImport
      parentRoute: typeof ProgettiRoute
    }
    '/en/services': {
      id: '/en/services'
      path: '/en/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects': {
      id: '/en/projects'
      path: '/en/projects'
      fullPath: '/en/projects'
      preLoaderRoute: typeof EnProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/cookie-policy': {
      id: '/en/cookie-policy'
      path: '/en/cookie-policy'
      fullPath: '/en/cookie-policy'
      preLoaderRoute: typeof EnCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact-privacy': {
      id: '/en/contact-privacy'
      path: '/en/contact-privacy'
      fullPath: '/en/contact-privacy'
      preLoaderRoute: typeof EnContactPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgettiRouteChildren {
  ProgettiReverseEngineeringStaffaAutomotiveRoute: typeof ProgettiReverseEngineeringStaffaAutomotiveRoute
}

const ProgettiRouteChildren: ProgettiRouteChildren = {
  ProgettiReverseEngineeringStaffaAutomotiveRoute:
    ProgettiReverseEngineeringStaffaAutomotiveRoute,
}

const ProgettiRouteWithChildren = ProgettiRoute._addFileChildren(
  ProgettiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  PrivacyContattiRoute: PrivacyContattiRoute,
  ProgettiRoute: ProgettiRouteWithChildren,
  ReverseEngineeringRoute: ReverseEngineeringRoute,
  ServiziRoute: ServiziRoute,
  ApiContactRoute: ApiContactRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnContactPrivacyRoute: EnContactPrivacyRoute,
  EnCookiePolicyRoute: EnCookiePolicyRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnProjectsRoute: EnProjectsRoute,
  EnServicesRoute: EnServicesRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
